-- Schema for the `readings` table used by this app.
--
-- Run this in the Supabase SQL editor (Dashboard → SQL Editor → New query).
-- It is idempotent: safe to run on the existing project, where `readings`
-- already exists with columns (id, book, chapter, "user", created_at) but is
-- missing the `date` column the app stores the reading day in.

create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  book text not null,
  chapter int not null,
  "user" uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- The day the chapter was read (user-pickable, unlike created_at).
alter table public.readings
  add column if not exists date date not null default current_date;

-- Let inserts omit the user column entirely.
alter table public.readings
  alter column "user" set default auth.uid();

alter table public.readings enable row level security;

drop policy if exists "Users can read own readings" on public.readings;
create policy "Users can read own readings"
  on public.readings for select
  to authenticated
  using ((select auth.uid()) = "user");

drop policy if exists "Users can insert own readings" on public.readings;
create policy "Users can insert own readings"
  on public.readings for insert
  to authenticated
  with check ((select auth.uid()) = "user");

drop policy if exists "Users can delete own readings" on public.readings;
create policy "Users can delete own readings"
  on public.readings for delete
  to authenticated
  using ((select auth.uid()) = "user");

create index if not exists readings_user_date_idx
  on public.readings ("user", date);
